namespace: epfl_si
name: podman
version: 0.1.0
readme: README.md
authors:
- EPFL ISAS-FSD <isas-fsd@groupes.epfl.ch>

description: Ansible collection to manage Podman containers beyond what `containers.podman` provides

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
license:
- GPL-2.0

tags: []
dependencies:
  epfl_si.actions: ">=1.0.0"
repository: https://github.com/epfl-si/ansible-collection-podman
homepage: https://github.com/epfl-si/ansible-collection-podman
documentation: https://github.com/epfl-si/ansible-collection-podman
issues: https://github.com/epfl-si/ansible-collection-podman/issues

build_ignore: []

